packages/threat-statement-generator/src/contexts/ThreatsContext/index.tsx, packages/threat-statement-generator/src/utils/renderThreatStatement/index.ts
=> fix: Fix an issue where prerequisite was not rendered properly

packages/threat-statement-generator/src/components/application/ApplicationInfo/index.tsx, packages/threat-statement-generator/src/components/assumptions/AssumptionCard/index.tsx, packages/threat-statement-generator/src/components/assumptions/AssumptionCreationCard/index.tsx, packages/threat-statement-generator/src/components/assumptions/AssumptionLink/index.tsx, packages/threat-statement-generator/src/components/assumptions/AssumptionLinkView/index.tsx, packages/threat-statement-generator/src/components/assumptions/AssumptionList/index.tsx, packages/threat-statement-generator/src/components/assumptions/AssumptionMitigationLink/index.tsx, packages/threat-statement-generator/src/components/generic/BaseDiagramInfo/index.tsx, packages/threat-statement-generator/src/components/generic/CommentsEdit/index.tsx, packages/threat-statement-generator/src/components/generic/EntityMetadataEditor/index.tsx, packages/threat-statement-generator/src/components/generic/GenericEntityCreationCard/index.tsx, packages/threat-statement-generator/src/components/generic/LinkedEntityFilter/index.tsx, packages/threat-statement-generator/src/components/generic/MarkdownEditor/index.tsx, packages/threat-statement-generator/src/components/generic/Tooltip/index.css, packages/threat-statement-generator/src/components/mitigations/MitigationCard/index.tsx, packages/threat-statement-generator/src/components/mitigations/MitigationCreationCard/index.tsx, packages/threat-statement-generator/src/components/mitigations/MitigationLink/index.tsx, packages/threat-statement-generator/src/components/mitigations/MitigationLinkView/index.tsx, packages/threat-statement-generator/src/components/mitigations/MitigationList/index.tsx, packages/threat-statement-generator/src/components/report/ThreatModel/components/ThreatModelView/index.tsx, packages/threat-statement-generator/src/components/report/ThreatModel/utils/getAssets/index.ts, packages/threat-statement-generator/src/components/report/ThreatModel/utils/getMitigations/index.ts, packages/threat-statement-generator/src/components/report/ThreatModel/utils/getThreats/index.ts, packages/threat-statement-generator/src/components/threats/FieldSelector/index.tsx, packages/threat-statement-generator/src/components/threats/MetadataEditor/index.tsx, packages/threat-statement-generator/src/components/threats/ThreatLinkView/index.tsx, packages/threat-statement-generator/src/components/threats/ThreatStatementEditor/index.tsx, packages/threat-statement-generator/src/components/threats/ThreatStatementList/index.tsx, packages/threat-statement-generator/src/contexts/GlobalSetupContext/index.tsx, packages/threat-statement-generator/src/hooks/useEditMetadata/index.ts
=> feat: Misc features on full mode

.projen/tasks.json, .projenrc.ts, packages/threat-composer-infra/src/application-stack.ts
=> build: Add more http headers to CloudFront distribution

packages/threat-composer/src/components/generic/BaseDiagramInfo/index.tsx, packages/threat-composer/src/components/generic/ImageEdit/index.tsx, packages/threat-composer/src/components/threats/EditorThreatSource/index.tsx, packages/threat-composer/src/components/workspaces/EditWorkspace/index.tsx, packages/threat-composer/src/components/workspaces/WorkspaceSelector/index.tsx, packages/threat-composer/src/configs/content.ts, packages/threat-composer/src/contexts/ApplicationContext/index.tsx, packages/threat-composer/src/contexts/ArchitectureContext/index.tsx, packages/threat-composer/src/contexts/AssumptionLinksContext/index.tsx, packages/threat-composer/src/contexts/AssumptionsContext/index.tsx, packages/threat-composer/src/contexts/DataflowContext/index.tsx, packages/threat-composer/src/contexts/MitigationLinksContext/index.tsx, packages/threat-composer/src/contexts/MitigationsContext/index.tsx, packages/threat-composer/src/contexts/ThreatsContext/index.tsx, packages/threat-composer/src/hooks/useRemoveData/index.ts
=> chore: Add input validation to all inputs

packages/threat-composer-app/src/components/StandaloneAppLayout/index.tsx, packages/threat-composer/src/components/generic/ImageEdit/index.tsx, packages/threat-composer/src/components/threats/EditorPrerequisites/index.tsx, packages/threat-composer/src/components/threats/EditorThreatAction/index.tsx, packages/threat-composer/src/components/threats/EditorThreatImpact/index.tsx, packages/threat-composer/src/components/threats/EditorThreatSource/index.tsx, packages/threat-composer/src/configs/content.ts, packages/threat-composer/src/customTypes/entities.ts, packages/threat-composer/src/customTypes/workspaces.ts
=> fix: Allow users to remove images

packages/threat-composer/src/components/workspaces/WorkspaceInsights/components/ThreatGrammar/index.tsx
=> fix(WorkspaceInsights):  Fixing typo 'prerequistes' in dashboard widget

README.md, packages/threat-composer-infra/src/application-stack.ts
=> feat: Use SSM parameter to pass the lambda edge ARN from us-east-1 

packages/threat-composer-app/public/404.html, packages/threat-composer-app/src/containers/App/components/Full/index.tsx, packages/threat-composer/src/components/report/ThreatModel/components/ThreatModelView/index.tsx, packages/threat-composer/src/components/report/ThreatModel/index.tsx, packages/threat-composer/src/contexts/ContextAggregator/index.tsx, packages/threat-composer/src/contexts/ThreatsContext/index.tsx, packages/threat-composer/src/contexts/WorkspaceContextAggregator/index.tsx, packages/threat-composer/src/contexts/WorkspacesContext/context.ts, packages/threat-composer/src/contexts/WorkspacesContext/index.tsx, packages/threat-composer/src/customTypes/dataExchange.ts, packages/threat-composer/src/customTypes/events.ts, packages/threat-composer/src/hooks/useExportImport/index.ts, packages/threat-composer/src/hooks/useHasContent/index.tsx, packages/threat-composer/src/utils/hasContent/index.ts
this PR is to:
1) Add next step suggestions in ThreatModelView 
2) Add github pages 404 redirect
3) Update the export json file to remove the timestamp so that the file can be easily replaced the existing one
=> feat(ThreatModelView): Add next step suggestions

packages/threat-composer-app/public/404.html, packages/threat-composer-app/public/index.html
=> build: Fix the GitHub Pages 404 issue

packages/threat-composer-app/src/containers/App/index.tsx, packages/threat-composer-app/src/containers/ThreatModelReport/index.tsx, packages/threat-composer-app/src/utils/generateUrl/index.ts
=> fix: Fix an issue where the add new statement button is not working in full mode

packages/threat-composer/src/hooks/useExportImport/index.ts
=> fix: Remove workspace Id from export json file

README.md, packages/threat-composer/src/components/workspaces/LandingPage/index.tsx
- Updated guidance in README and Landing Page on how to use the 'Example' workspace
=> doc: Updated guidance on using Example workspace

packages/threat-composer/src/components/report/ThreatModel/components/ThreatModelView/index.tsx, packages/threat-composer/src/components/report/ThreatModel/index.tsx, packages/threat-composer/src/hooks/useExportImport/index.ts, packages/threat-composer/src/utils/downloadObjectAsMarkdown/index.ts, packages/threat-composer/src/utils/getExportFileName/index.ts
This PR is to:
* Allow users to download the ThreatModel as markdown file
* Fix an issue where the preview was not working in Import 
=> feat(ThreatModelView): Allow users to download the markdown file

packages/threat-composer/src/contexts/ThreatsContext/components/LocalStateContextProvider/index.tsx, packages/threat-composer/src/contexts/ThreatsContext/components/LocalStorageContextProvider/index.tsx
=> fix(Threats): Fix an issue where only one threat can be edited in parallel in Full mode

.projenrc.ts, packages/threat-composer/.projen/deps.json, packages/threat-composer/package.json, yarn.lock
Upgrade `@babel/preset-env` from `7.21.4` to `7.23.2`
=> build(deps): @babel/preset-env

packages/threat-composer/src/hooks/useExportImport/index.ts, packages/threat-composer/src/utils/cleanupThreatData/index.ts, packages/threat-composer/src/utils/recalculateThreatData/index.ts
=> fix: Remove unused nodes from exported json file and rename exported json file

packages/threat-composer/src/components/workspaces/WorkspaceInsights/index.tsx, packages/threat-composer/src/hooks/useExportImport/index.ts, packages/threat-composer/src/utils/cleanupThreatData/index.ts, packages/threat-composer/src/utils/recalculateThreatData/index.ts
- Show the application name (if available) in the dashboard
- Fixes eslint formatting missed in recent commit
=> feat(WorkspaceInsights): Show application name

packages/threat-composer/src/data/workspaceExamples/ThreatComposer.tc.json, packages/threat-composer/src/data/workspaceExamples/workspaceExamples.ts
=> feat(ThreatComposerThreatModel): Additional threats and new export format

packages/threat-composer/src/components/workspaces/WorkspaceSelector/index.tsx, packages/threat-composer/src/contexts/ApplicationContext/index.tsx, packages/threat-composer/src/contexts/ArchitectureContext/index.tsx, packages/threat-composer/src/contexts/AssumptionLinksContext/index.tsx, packages/threat-composer/src/contexts/AssumptionsContext/index.tsx, packages/threat-composer/src/contexts/DataflowContext/index.tsx, packages/threat-composer/src/contexts/MitigationLinksContext/index.tsx, packages/threat-composer/src/contexts/MitigationsContext/index.tsx, packages/threat-composer/src/contexts/ThreatsContext/index.tsx, packages/threat-composer/src/contexts/WorkspaceExamplesContext/context.ts, packages/threat-composer/src/contexts/WorkspaceExamplesContext/index.tsx, packages/threat-composer/src/customTypes/dataExchange.ts
=> chore: Fix the examples navigation

.projenrc.ts, packages/threat-composer-app-browser-extension/.projen/tasks.json, packages/threat-composer-app-browser-extension/wxt.config.ts
Cleaner implementation of build scripts and manifest compatibility
=> chore(Browser extension): Improve build scripts

packages/threat-composer-app/src/containers/App/components/Full/index.tsx, packages/threat-composer-app/src/containers/MitigationPacks/index.tsx, packages/threat-composer-app/src/containers/ThreatPack/index.tsx, packages/threat-composer-app/src/containers/ThreatStatementEditor/index.tsx, packages/threat-composer-app/src/index.tsx, packages/threat-composer-app/src/utils/isMemoryRouterUsed/index.ts, packages/threat-composer/src/components/generic/DashboardNumber/index.tsx, packages/threat-composer/src/components/workspaces/MitigationPacks/index.tsx, packages/threat-composer/src/components/workspaces/ThreatPacks/index.tsx, packages/threat-composer/src/components/workspaces/WorkspaceInsights/components/Overview/index.tsx, packages/threat-composer/src/components/workspaces/WorkspaceInsights/components/STRIDEAllocation/index.tsx, packages/threat-composer/src/components/workspaces/WorkspaceInsights/components/ThreatGrammar/index.tsx, packages/threat-composer/src/components/workspaces/WorkspaceInsights/components/ThreatPrioritization/index.tsx
=> chore: Fix issues re: Memory Router

packages/threat-composer-app/src/components/FullAppLayout/index.tsx
=> chore: Stop the link propagation on the navigation items

.gitignore, .projen/deps.json, .projen/tasks.json, package.json, packages/threat-composer-app-browser-extension/.projen/deps.json, packages/threat-composer-app-browser-extension/package.json, packages/threat-composer-app/.projen/deps.json, packages/threat-composer-app/package.json, packages/threat-composer-infra/.projen/deps.json, packages/threat-composer-infra/package.json, packages/threat-composer/.projen/deps.json, packages/threat-composer/package.json, yarn.lock
=> fix: Upgrade pdk to fix the web acl deployment issue

packages/threat-composer-app/public/index.html
=> fix: Move the ide-toolkits urls to default-src in the csp

packages/threat-composer-infra/src/application-stage.ts
=> fix: Fix an issue where not all Prod envs have termination protection

packages/threat-composer/src/components/workspaces/EditWorkspace/index.tsx, packages/threat-composer/src/components/workspaces/WorkspaceSelector/index.tsx, packages/threat-composer/src/contexts/WorkspacesContext/index.tsx
=> fix: Fix an issue where add/edit workspace is not working properly when same workspace name is used

packages/threat-composer/src/configs/content.ts
=> fix: Fix an issue when importing file including image/svg+xml images causes validation error. Close #100

packages/threat-composer/src/configs/events.ts, packages/threat-composer/src/contexts/GlobalSetupContext/context.ts, packages/threat-composer/src/contexts/GlobalSetupContext/index.tsx, packages/threat-composer/src/contexts/WorkspacesContext/components/LocalStateContextProvider/index.tsx, packages/threat-composer/src/contexts/WorkspacesContext/components/LocalStorageContextProvider/index.tsx, packages/threat-composer/src/contexts/WorkspacesContext/index.tsx, packages/threat-composer/src/contexts/WorkspacesContext/types.ts, packages/threat-composer/src/contexts/WorkspacesContext/useWorkspaces.ts, packages/threat-composer/src/customTypes/appMode.ts, packages/threat-composer/src/hooks/useWorkspaceStorage/index.ts
=> chore: Implement local state for IDE toolkit use case

packages/threat-composer-infra/cdk.context.json, packages/threat-composer-infra/src/application-stack.ts
=> feat: Support configuration of cache control

package.json, packages/threat-composer-infra/package.json, packages/threat-composer-infra/test/__snapshots__/pipeline.test.ts.snap, packages/threat-composer/src/components/workspaces/WorkspaceSelector/index.tsx, yarn.lock
=> build(deps-dev): Bump @aws/pdk version

packages/threat-composer-app/src/containers/ThreatStatementEditor/index.tsx, packages/threat-composer/src/components/threats/ThreatStatementEditor/index.tsx, packages/threat-composer/src/contexts/ThreatsContext/hooks/useThreats/index.ts, packages/threat-composer/src/utils/getNewThreatStatement/index.tsx, packages/threat-composer/src/utils/getThreatFromThreatPacksThreat/index.ts
=> fix: Fix an issue where the StartOver button in Threat Editor was not working

README.md, packages/threat-composer-app/src/components/Notifications/index.tsx
Flashbar message and README update to inform GitHub pages demo site users of the threat composer feature within AWS Toolkit VS code extension
=> feat: VS Code extension announcement

packages/threat-composer/src/data/workspaceExamples/ThreatComposer.tc.json
Updated the Threat Composer threat model (WorkspaceExample) with Threat and Mitigation statuses
=> doc(ThreatComposerThreatModel): Update threat and mitigation status

packages/threat-composer-app/src/containers/ThreatStatementEditor/index.tsx, packages/threat-composer/src/components/generic/Table/index.tsx, packages/threat-composer/src/components/mitigations/MitigationLinkView/index.tsx, packages/threat-composer/src/components/threats/FieldSelector/index.tsx, packages/threat-composer/src/components/threats/Header/index.tsx, packages/threat-composer/src/components/threats/MitigationCandidates/index.tsx, packages/threat-composer/src/components/threats/ThreatStatementEditor/index.tsx, packages/threat-composer/src/components/workspaces/MitigationPack/index.tsx, packages/threat-composer/src/components/workspaces/MitigationPacks/index.tsx, packages/threat-composer/src/components/workspaces/ThreatPack/index.tsx, packages/threat-composer/src/components/workspaces/ThreatPacks/index.tsx, packages/threat-composer/src/contexts/ThreatPacksContext/context.ts, packages/threat-composer/src/contexts/ThreatPacksContext/index.tsx, packages/threat-composer/src/customTypes/referencePacks.ts, packages/threat-composer/src/data/threatPacks/generated/GenAIChatbot.json, packages/threat-composer/src/utils/matchThreatPackMitigationCandidate/index.ts, scripts/packs/buildPacks.ts
=> feat: Support Mitigation Candidates for Threat Packs

.gitignore, .projen/deps.json, package.json, packages/threat-composer-app-browser-extension/.gitignore, packages/threat-composer-app-browser-extension/.projen/deps.json, packages/threat-composer-app-browser-extension/package.json, packages/threat-composer-app/.gitignore, packages/threat-composer-app/.projen/deps.json, packages/threat-composer-app/package.json, packages/threat-composer-infra/.gitignore, packages/threat-composer-infra/.projen/deps.json, packages/threat-composer-infra/package.json, packages/threat-composer/.gitignore, packages/threat-composer/.projen/deps.json, packages/threat-composer/package.json, packages/threat-composer/src/components/generic/Table/components/FullDataTable/index.tsx, packages/threat-composer/src/components/workspaces/ThreatPack/index.tsx, projenrc/browser-extension.ts, projenrc/monorepo.ts, yarn.lock
=> build(deps): Bump versions of dependencies - projen, nx, ws, @aws-sdk* and fast-xml-parser

packages/threat-composer-app/src/utils/isMemoryRouterUsed/index.ts, packages/threat-composer/src/components/report/ThreatModel/index.tsx
=> fix: memory router mode for browser extension

README.md
n/a
Updated 192.160.0.0/24 to 192.168.0.0/24, as 192.160.0.0/24 is a) routable which is contrary to what’s stated, and b) not referenced anywhere else in the code.
=> Update README.md - typo correction

.github/workflows/deploy.yml
=> build: Update version of actions/upload-pages-artifact

.github/workflows/deploy.yml
=> build: Update version of actions/deploy-pages

scripts/build.sh
=> fix(build): Revert the changes on build script

.gitlab-ci.yml.example, Dockerfile, projenrc/app.ts, scripts/build.sh, yarn.lock
*Issue #164*
Update the Dockerfile to make it easy to deploy a self-hosted version
I've made updates to the Dockerfile to depend on amazon linux and then build the project. I've also added a dev dependency to get rid of a react warning. 
Note that the build script works locally on my mac, but I cannot get the code to build in a container as I suspect that when running `npx storybook...` the `node` process runs out of memory and is killed. I need to test this by using a VM with more memory or test it out on EC2, which I have not done yet.
=> build: Update Dockerfile and add a sample Gitlab CI/CD YAML file

packages/threat-composer/src/data/mitigationPacks/generated/GenAIChatbot.json, packages/threat-composer/src/data/threatPacks/generated/GenAIChatbot.json
Updated Threat and Mitigation packs based on updated GenAI chatbot workspace example - See #175 
=> feat: Updated GenAi threat / migiation packs to align with the updated workspace example

.projen/tasks.json, package.json, packages/threat-composer-infra/package.json, yarn.lock
Upgrading PDK dep to address [OOM issue](https://github.com/aws/aws-pdk/issues/909)
=> fix(deps): Bump @aws/pdk from 0.26.6 to 0.26.14
