packages/threat-statement-generator-demo-app/src/components/AppLayout/components/NavHeader/index.tsx
packages/threat-statement-generator-demo-app/src/components/AppLayout/index.tsx
packages/threat-statement-generator/src/components/generic/Tooltip/index.css
packages/threat-statement-generator/src/components/generic/Tooltip/index.tsx
packages/threat-statement-generator/src/components/threats/ThreatStatementEditor/index.tsx
packages/threat-statement-generator/src/utils/renderThreatStatement/index.ts

This PR is to 
* fix the header href so that it can be used for Github page and different mode settings
* use bottom tooltip for EditorOnly mode so that users can see the full tooltip (was blocked to limited space on the top)
* fix the rendered statements where these is extra space before the comma

fix: Fix the header href

---

packages/threat-composer/src/components/generic/Autosuggest/index.tsx
packages/threat-composer/src/components/generic/Textarea/index.tsx
packages/threat-composer/src/components/threats/EditorImpactedAssets/index.tsx
packages/threat-composer/src/components/threats/EditorImpactedGoal/index.tsx
packages/threat-composer/src/components/threats/EditorPrerequisites/index.tsx
packages/threat-composer/src/components/threats/EditorThreatAction/index.tsx
packages/threat-composer/src/components/threats/EditorThreatImpact/index.tsx
packages/threat-composer/src/customTypes/threats.ts
packages/threat-composer/src/hooks/useContentValidation/index.tsx

#17 
This PR is to add  input validation to ImpactedAssets and ImpactedGoal editors to show warning messages when potential html tags are entered by the users so that the output in the threat statement list and threat model are consistent. 

fix: Add input validation to ImpactedAssets and ImpactedGoal editors. Close #17. 

---

packages/threat-composer-infra/src/application-stack.ts
packages/threat-composer/src/containers/LandingPage/index.tsx

The infra deployment will fail if lambda edge ARN is provided because [lambda edge cannot be used together with CloudFunction on viewer request event](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html).
The solution here is to use custom ResponseHeadersPolicy to inject security headers.

fix: Fix an issue where the deployment failed if lambda edge is used with Cloud Function

---

packages/threat-composer/src/components/application/ApplicationInfo/index.tsx
packages/threat-composer/src/components/architecture/ArchitectureInfo/index.tsx
packages/threat-composer/src/components/assumptions/AssumptionList/index.tsx
packages/threat-composer/src/components/dataflow/DataflowInfo/index.tsx
packages/threat-composer/src/components/generic/AssetSelector/index.tsx
packages/threat-composer/src/components/generic/BaseDiagramInfo/index.tsx
packages/threat-composer/src/components/generic/TagSelector/index.tsx
packages/threat-composer/src/components/mitigations/MitigationList/index.tsx
packages/threat-composer/src/components/threats/ThreatStatementList/index.tsx
packages/threat-composer/src/components/workspaces/WorkspaceSelector/index.tsx
packages/threat-composer/src/customTypes/components.ts

This PR includes changes:
* Sort tags in alphabetic order and allow filtering on tags
* Sort assets in alphabetic order and allow filtering on assets
* Move the **Add new workspace** button into the dropdown menu

feat: Sort tags/assets in alphabetic order and allow filtering on tags/assets

---

packages/threat-composer-app/public/404.html
packages/threat-composer-app/public/index.html
packages/threat-composer-app/src/components/GithubPagesNavigationHelper/index.tsx
packages/threat-composer-app/src/components/Notifications/index.tsx
packages/threat-composer-app/src/containers/App/index.tsx
packages/threat-composer-app/src/containers/ThreatModelReport/index.tsx
packages/threat-composer/src/components/report/ThreatModel/components/ThreatModelView/index.tsx
packages/threat-composer/src/components/report/ThreatModel/index.tsx

This PR includes:
* Fix an issue where GitHub Pages 404 redirect is not working due to CSP inline restriction by moving the redirect logic inside the react app
* Disable next steps actions for Preview pages
* Only display Github Notifications once per session

fix: Fix an issue where Github pages 404 redirect is not working

---

packages/threat-composer/src/components/workspaces/LandingPage/index.tsx
packages/threat-composer/src/components/workspaces/WorkspaceSelector/index.tsx
packages/threat-composer/src/contexts/GlobalSetupContext/context.ts
packages/threat-composer/src/contexts/GlobalSetupContext/index.tsx

fix: Fix an issue where the import modal popup when switching workspace

---

packages/threat-composer-app/src/components/FullAppLayout/index.tsx
packages/threat-composer-app/src/config/routes.ts
packages/threat-composer-app/src/containers/App/components/Full/index.tsx
packages/threat-composer-app/src/hooks/useSetActiveBreadCrumbs/index.ts

- Renames 'Home' to 'Dashboard' for better discoverability of Insights Dashboard feature

feat(App): Rename 'Home' to 'Dashboard'

---

packages/threat-composer/src/components/generic/FileUpload/components/FileTokenLabel/index.tsx
packages/threat-composer/src/components/generic/FileUpload/index.tsx
packages/threat-composer/src/components/generic/FileUpload/utils/getDisplaySize/index.ts
packages/threat-composer/src/components/generic/ImageEdit/index.tsx
packages/threat-composer/src/configs/constants.ts

#62 
Currently, we have set the image base64 size limit to 500000 to encourage users to upload smaller size images because of very limited local storage space. However, when users upload an image file with more that 500K, we do not show the error message until users export and reimport the json file. The validation failed. 
The PR is to increase the file size limit and also show the error message. 

fix: Fix the issue where import failed without clear prompt when image size exceeds the maximum size file. Close #62

---

scripts/deployAll.sh
scripts/deployDev.sh

Added the missing `@aws/` prefix from the `./scripts/deployDev.sh` and `./script/deployAll.sh` scripts.

fix(Build): Added package prefix to build scripts

---

packages/threat-composer/src/components/generic/WindowExporter/index.tsx
packages/threat-composer/src/components/report/ThreatModel/components/ThreatModelView/index.tsx
packages/threat-composer/src/contexts/GlobalSetupContext/index.tsx
packages/threat-composer/src/customTypes/dataExchange.ts
packages/threat-composer/src/customTypes/windowAPI.ts

Add `applyTheme` and `applyDensity` to window API. 
To apply dark theme, run `window.threatcomposer.applyTheme('dark')`

chore: Support applyTheme from window API

---

packages/threat-composer-app-browser-extension/wxt.config.ts

Update build transforms to remove references to remote script (not permitted in Manifest V3)

chore(Browser extension): Remove remote scripts

---

packages/threat-composer/src/components/threats/PriorityEdit/index.tsx

Fixing a minor spelling mistake in "Select Priority" dropdown.

fix: Spelling of "priority" in dropdown

---

packages/threat-composer/src/components/generic/ImageEdit/index.tsx

#84 
Allow all image formats (image/*) upload for architecture diagrams and dataflow diagrams. For 'image/png', 'image/gif', or 'image/jpeg', run the browser-image-compression plugin; for other images, keep the original format. The total number bytes of the resulted base64 encoded image is checked to ensure it is less than 1MB. 

feat: Support other image formats for architecture diagrams and dataflow diagrams. Close #84

---

packages/threat-composer-app/public/index.html
packages/threat-composer-app/src/components/NavHeader/index.tsx
packages/threat-composer-app/src/config/searchParams.ts
packages/threat-composer-app/src/containers/App/index.tsx
packages/threat-composer-app/src/index.tsx
packages/threat-composer/.storybook/preview.tsx
packages/threat-composer/src/components/generic/ThemeProvider/index.tsx
packages/threat-composer/src/components/generic/WindowExporter/index.tsx
packages/threat-composer/src/components/index.ts
packages/threat-composer/src/contexts/GlobalSetupContext/index.tsx
packages/threat-composer/src/hooks/useExportImport/index.ts

chore: Set initial theme as per prefers-color-scheme system settings

---

packages/threat-composer/src/components/assumptions/AssumptionCreationCard/index.tsx
packages/threat-composer/src/components/mitigations/MitigationCreationCard/index.tsx
packages/threat-composer/src/components/workspaces/WorkspaceInsights/components/STRIDEAllocation/index.tsx
packages/threat-composer/src/components/workspaces/WorkspaceInsights/components/ThreatGrammar/index.tsx
packages/threat-composer/src/components/workspaces/WorkspaceInsights/components/ThreatPrioritization/index.tsx
packages/threat-composer/src/contexts/ContextAggregator/index.tsx

This PR is to:
1) Fix an issue where the add threat links are not working at the Workspace Insight
2) Add validation to Mitigation Creation/Assumption Creation Card

fix: Fix an issue where the add threat links are not working at the Workspace Insight

---

packages/threat-composer-app-browser-extension/src/entrypoints/background.ts
packages/threat-composer-app-browser-extension/src/public/scriptInjectForThreatComposer.js
packages/threat-composer-app-browser-extension/wxt.config.ts

Change threat model reload behaviour to no longer reload the threat model on visibility changes of the window/tab, as it would result in overwriting any unexported changes a user has performed.

chore(Browser extension): Remove reload of threat model on visibility

---

packages/threat-composer-app/src/containers/WorkspaceSelector/index.tsx
packages/threat-composer/src/configs/content.ts
packages/threat-composer/src/contexts/WorkspacesContext/components/LocalStateContextProvider/index.tsx
packages/threat-composer/src/contexts/WorkspacesContext/components/LocalStorageContextProvider/index.tsx
packages/threat-composer/src/contexts/WorkspacesContext/useCurrentWorkspace.ts
packages/threat-composer/src/customTypes/workspaces.ts

This PR is to:
* Redirect initial url including invalid workspace name to the last visited workspace
* Hide Preview button in the IDE-Extension mode since the Preview is open in another tab which is not supported in IDE
* Set Constraint on workspace name so that it will not cause routing issue

fix: Redirect invalid workspace name to the last visited workspace

---

packages/threat-composer-app/.projen/deps.json
packages/threat-composer-app/.projen/tasks.json
packages/threat-composer-app/package.json
packages/threat-composer-app/src/containers/ThreatModelPreview/index.tsx
packages/threat-composer/src/components/generic/ThemeToggle/index.tsx
packages/threat-composer/src/components/workspaces/WorkspaceSelector/index.tsx
projenrc/app.ts
yarn.lock

This PR is to fix the dark theme for the ThreatModel Print Preview Page. And also hide the theme toggle on Mobile pages since there is no enough space when the workspace name is long. 

fix: Fix the dark theme in ThreatModel Print Preview page

---

Dockerfile

…ode from checkout and subsequently copies the website folder into a second stage image that runs the website via nginx
*Issue #97 :* 
Adds a two-stage docker container that builds a container to build the code and run the application containerized. The container uses the aws-pdk container image to build the first stage and the alpine-nginx to serve the application. 
Note that serving happens by default on 80. We assume that the image is run locally over a laptop. If additional SSL/TLS implementation is required it must be done by the user at the loadbalancer level. 

feat: Multi-stage build Dockerfile for building and serving threat composer. Close #97

---

README.md

- Corrected commands `yarn run build:packs` (i.e not `yarn run build:pack`)
- Corrected `MitigationPack[]` (i.e. not `ThreatPack[]` in Mitigation Pack section)

doc(README): Threat / Mitigation Packs - Fix instructions

---

scripts/data/injectData.ts

This PR is to update the injectData script to restructure the name of dynamically imported workspace examples from the file name. 

fix(build): Restructure the workspace examples dynamic import name

---

scripts/build.sh
scripts/deployAll.sh
scripts/deployDev.sh

*Issue #, if available:* N/A
In `build.sh`, the invocation to PDK had extra sets of tokens that were unneeded; I have removed those.
In both `deployAll.sh` and `deployDev.sh`, `pdk` referred to projen tasks (`workspace`, `run`) that didn't exist; I have reverted the PDK invocation to use `yarn` instead.

fix(build): repair pdk yarn invocations

---

packages/threat-composer/src/components/generic/MarkdownEditor/index.tsx

- Added support for thematic breaks in the Markdown editor (`mdxeditor`)

fix(mdxeditor): Add Markdown thematic break support
